complex_thought_planning:
  description: >
    Ação esperada identificada pelo cortex pré-frontal: {acao_esperada}
    Atribuição recebida: {complex_thought_planner}
  expected_output: >
    Um modelo de pensamento complexo que inclui:
    - Se aplicável, análise detalhada de informações relevantes e interconectadas.
    - Se aplicável, identificação de padrões e relações entre variáveis.
    - Se aplicável, geração de insights profundos e soluções inovadoras.
    - Se aplicável, consideração das implicações de diferentes opções e cenários.
    - Se aplicável, um plano estratégico que reflete a compreensão abrangente do problema.
