prefrontal_behavior_planning:
  description: >
    A tarefa de planejamento de comportamentos do córtex pré-frontal envolve a definição e 
    organização de comportamentos adaptativos que o sistema deve adotar para atingir seus 
    objetivos. O Planner deve identificar as ações apropriadas para diferentes cenários, 
    avaliar o impacto dessas ações e ajustar o comportamento com base em feedback e novas informações.
  expected_output: >
    Um conjunto de comportamentos adaptativos que inclui:
    - Padrões de comportamento definidos para diferentes situações.
    - Estratégias para ajustar o comportamento com base em feedback e mudanças no ambiente.
    - Mecanismos para monitorar e avaliar a eficácia dos comportamentos implementados.
    - Planos de contingência para lidar com imprevistos e novas informações.
  
complex_thought_planning:
  description: >
    A tarefa de planejamento de pensamentos complexos envolve a integração e análise de 
    informações multifacetadas para gerar insights e soluções avançadas. O Complex Thought 
    Planner deve considerar diferentes perspectivas, identificar padrões e prever as 
    implicações de diferentes abordagens. A tarefa requer uma combinação de pensamento 
    analítico e criativo para resolver problemas complexos.
  expected_output: >
    Um modelo de pensamento complexo que inclui:
    - Análise detalhada de informações relevantes e interconectadas.
    - Identificação de padrões e relações entre variáveis.
    - Geração de insights profundos e soluções inovadoras.
    - Consideração das implicações de diferentes opções e cenários.
    - Um plano estratégico que reflete a compreensão abrangente do problema.

decision_making:
  description: >
    A tarefa de tomada de decisões envolve a análise de opções disponíveis e a escolha 
    da melhor alternativa com base em critérios definidos. O Decision Maker deve 
    avaliar informações relevantes, considerar possíveis consequências e fazer uma 
    escolha estratégica que atenda aos objetivos do sistema. A tarefa também pode 
    incluir a revisão de decisões passadas e ajustes baseados em novos dados ou feedback.
  expected_output: >
    Uma decisão clara e justificada que inclui:
    - Análise das opções disponíveis e seus prós e contras.
    - Avaliação das implicações de cada opção em relação aos objetivos do sistema.
    - Escolha da alternativa mais eficaz, com uma justificativa detalhada.
    - Plano de ação para implementar a decisão tomada.
    - Mecanismos para monitorar os resultados e ajustar a decisão conforme necessário.

social_behavior_modulation:
  description: >
    A tarefa de modulação de comportamento social envolve a adaptação do comportamento 
    do sistema para atender às expectativas sociais e contextuais. O Social Behavior 
    Modulator deve analisar o contexto social, ajustar o comportamento do sistema 
    para se alinhar com normas e expectativas, e garantir interações positivas e 
    respeitosas. Isso pode incluir a gestão de respostas a diferentes tipos de feedback 
    e a adaptação às mudanças nas dinâmicas sociais.
  expected_output: >
    Um plano de modulação de comportamento social que inclui:
    - Diretrizes para o comportamento em diferentes contextos sociais.
    - Estratégias para ajustar o comportamento com base no feedback e nas dinâmicas sociais.
    - Exemplos de respostas e interações que promovem relações positivas e respeitosas.
    - Mecanismos para monitorar e avaliar a eficácia das interações sociais.
    - Ajustes contínuos para melhorar a adequação e eficácia do comportamento social do sistema.
