social_behavior_modulation:
  description: >
    Ação esperada identificada pelo cortex pré-frontal: {acao_esperada}
    Atribuição recebida: {social_behavior_modulator}
  expected_output: >
    Um plano de modulação de comportamento social que inclui:
    - Diretrizes para o comportamento em diferentes contextos sociais.
    - Exemplos de respostas e interações que promovem relações positivas e respeitosas.
    - Estratégias para ajustar o comportamento com base no feedback e nas dinâmicas sociais.
    - Mecanismos para monitorar e avaliar a eficácia das interações sociais.
