personality_expression_planning:
  description: >
    A tarefa de planejamento da expressão da personalidade envolve a definição e gestão de como a personalidade do sistema é comunicada e expressa em diferentes contextos e interações. O Personality Express Planner deve considerar fatores como o público-alvo, o contexto da interação e os objetivos do sistema para garantir que a expressão da personalidade seja apropriada e eficaz.
  expected_output: >
    Um plano detalhado para a expressão da personalidade que inclui:
    - Diretrizes para a manifestação da personalidade em diferentes contextos e interações.
    - Exemplos de respostas e comportamentos que refletem a personalidade definida.
    - Estratégias para ajustar a expressão da personalidade com base no feedback e nas necessidades do usuário.
    - Mecanismos para assegurar a consistência e autenticidade da personalidade ao longo do tempo.
