personality_expression_planning:
  description: >
    Ação esperada identificada pelo cortex pré-frontal: {acao_esperada}
    Atribuição recebida: {personality_expression_planner}
  expected_output: >
    Um plano detalhado para a expressão da personalidade que inclui:
    - Diretrizes para a manifestação da personalidade em diferentes contextos e interações.
    - Exemplos de respostas e comportamentos que refletem a personalidade definida.
    - Estratégias para ajustar a expressão da personalidade com base no feedback e nas necessidades do usuário.
    - Mecanismos para assegurar a consistência e autenticidade da personalidade ao longo do tempo.
