prefrontal_management:
  description: >
    Identificar a ação esperada para a entrada: {input}
    O Prefrontal Manager deve raciocinar sobre quais ações devem ser tomadas e como essas 
    ações serão distribuídas entre os agentes. A tarefa envolve criar um plano estratégico 
    que define claramente como cada agente contribuirá para o objetivo global.
  expected_output: >
    Identificação da ação esperada e um plano estratégico para distribuir as tarefas entre os 
    agentes.
    behavior_planner(Gerenciador de comportamentos complexos e adaptativos)
    decision_maker(Tomador de decisões)
    social_behavior_modulator(Modulador de comportamento social)
    complex_thought_planner(Planejador de pensamento complexo)
    personality_express_planner(Planejador de personalidade)

