behavior_planning:
  description: >
    Ação esperada identificada pelo cortex pré-frontal: {acao_esperada}
    Atribuição recebida: {behavior_planner}
  expected_output: >
    Um conjunto de comportamentos adaptativos que inclui:
    - Comportamento atual
    - Comportamentos alternativos
    - Mecanismos para monitorar e avaliar a eficácia dos comportamentos implementados.
    - Planos de contingência para lidar com imprevistos e novas informações.
