prefrontal_management:
  description: >
    Entrada inicial: {input}

    Decisão inicial: {acao_esperada}

    Decisões avaliada pelo decision_maker:
    Decisões disponíveis: {available_decisions}
    Implicações: {implications}
    Decisão ótima: {optimal_decision}
    Estratégia de decisão: {decision_strategy}
    Consistência nas decisões: {decision_consistency}

    Combine as informações e tome a decisão final.
  expected_output: >
    Resposta apropriada ou ação a ser tomada.

